---
- name: copy from local
  copy:
    src: vars/test.py
    dest: /tmp/test.py
    mode: 0755


- name: run script
  command: "python test.py"
  args:
    chdir: /tmp/
  delegate_to: 127.0.0.1
  run_once: true
