---
- hosts: nxos
  connection: local
  gather_facts: no
  vars:
    cli:
      username: admin
      password: admin
  
  tasks:
  - nxos_command: 
      commands:
        - show run
      provider: "{{ cli }}"
