- debug: 
    msg: "START arista-os.yml"

# Backup config. Make sure to not run backup again in playbook, later runs overwrite this backup.
- name: Backup current config
  eos_config:
    backup: yes
    provider: "{{ cli }}"
  register: backup_config

- debug: 
    var: backup_config.backup_path
    verbosity: 3

- block:
    - name: Default NTP
      eos_config:
        lines: no {{ item }}
        provider: "{{ cli }}"
      with_items: "{{ config.cmds | select('match', 'ntp *') | list }}"

    - name: Configure NTP
      eos_config:
        src: arista-os.j2
        save: yes
        provider: "{{ cli }}"
        
  rescue:
    - debug: 
        var: backup_config.backup_path
        verbosity: 3

    - name: Reset to backed up config
      eos_config:
        src: "{{ backup_config.backup_path }}"
        save: yes
        provider: "{{ cli }}"
  
