- debug: 
    msg: "START cisco-ios-xr.yml"

# Backup config. Make sure to not run backup again in playbook, later runs overwrite this backup.
- name: Backup current config
  iosxr_config:
    backup: yes
    provider: "{{ cli }}"
  register: backup_config

- debug: 
    var: backup_config.backup_path
    verbosity: 3

- block:
    - name: Get ipv6 interface info
      iosxr_command:
        commands:
          - show ipv6 interface {{ mgmt_interface_name }}
        provider: "{{ cli }}"
      register: ipv6_interface

    - debug: 
        var: ipv6_interface
        verbosity: 3

    - name: Default NTP
      iosxr_config:
        lines: no ntp
        provider: "{{ cli }}"

    - name: Configure NTP
      iosxr_config:
        src: cisco-ios-xr.j2
        provider: "{{ cli }}"

  rescue:
    - debug: 
        var: backup_config.backup_path
        verbosity: 3

    - name: Reset to backed up config
      iosxr_config:
        src: "{{ backup_config.backup_path }}"
        provider: "{{ cli }}"
