---
- name: copy running-config startup-config
  nxos_command:
    commands:
      - copy running-config startup-config

- name: show startup-config
  nxos_command:
    commands:
      - show startup-config
  register: config

- name: write backup to file
  copy:
    content: "{{ config.stdout[0] }}"
    dest: "/backups/{{inventory_hostname}}_{{ansible_date_time.iso8601}}"
