---
- name: BASE NEIGHBOR CONFIG
  nxos_config:
    src: "{{ playbook_dir }}/roles/nxos_test/template/remove_bgp_spine_neighbor.j2"
    save_when: modified
#    provider: "{{ nxos_provider }}" #(nxapi)
  with_items:
    - "{{ bgp_neighbors }}"

- name: BASE NEIGHBOR CONFIG
  nxos_config:
    src: "{{ playbook_dir }}/roles/nxos_test/template/bgp_spine_neighbor.j2"
    save_when: modified
#    provider: "{{ nxos_provider }}" #(nxapi)
  with_items:
    - "{{ bgp_neighbors }}"