---
- name: show version
  nxos_command:
    commands:
      - show version
  register: version

- name: show vlan
  nxos_command:
    commands:
      - show vlan
  register: vlan

- name: show interface brief
  nxos_command:
    commands:
      - show interface brief
  register: int_brief

- name: show ip interface brief vrf all
  nxos_command:
    commands:
      - show ip interface brief vrf all
  register: ip_brief

- name: show ip route vrf all
  nxos_command:
    commands:
      - show ip route vrf all
  register: routing

- name: log version
  debug: msg="{{version.stdout[0] | regex_search('(system:.*version(.*))')}}"
  tags: log

- name: log uptime
  debug: msg="{{version.stdout[0] | regex_search('(uptime.*)')}}"
  tags: log

- name: log vlans
  debug: msg="{{(vlan.stdout[0] | regex_search('(VLAN.*\n--.*\n(.+\n)+)')).split('\n') }}"
  tags: log

- name: log ethernet interfaces
  debug: msg="{{(int_brief.stdout[0] | regex_search('(---.*\n.*Ethernet.*\n.+\n---.*\n(.*up.+\n)+)')).split('\n')}}"
  tags: log

- name: log ip interfaces
  debug: msg="{{ip_brief.stdout_lines}}"
  tags: log

- name: log routing
  debug: msg="{{routing.stdout_lines}}"
  tags: log
