galaxy_info:
  author: Bobby Watson (bwatsoni@cisco.com, robertwatson3@gmail.com)
  description: Installs NXOS and EPLD firmware on Nexus OS devices.
  company: Cisco Systems
  license: BSD
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - all
  - name: GenericUNIX
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: opensuse
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: SLES
    versions:
    - all
  - name: GenericLinux
    versions:
    - all
  - name: Debian
    versions:
    - all

  galaxy_tags:
    - nxos
    - networking
    - cisco
dependencies: []